#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_error:
    path: /{_locale}/error
    controller: App\Controller\ErrorController::error
    requirements:
        _locale: fr|en